apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-main
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-main
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-main
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-main
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
    spec:
      containers:
        - name: main
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
