apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-main
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-main
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: main.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-main
                port:
                  number: 80
